### ISSUE TITLE
When using Microsoft.AspNetCore.Mvc.Versioning and an unsupported version is requested, metrics are tagged incorrectly

### ISSUE THREAD

**Issue by alhardy** [AppMetrics/AspNetCore#25]
See discussion [here](https://github.com/AppMetrics/AppMetrics/issues/261#issuecomment-385653698)

**Comment by Kickeskov** [comment]
Is it currently possible to make a workaround when using Swagger and dotnet core 2.1 with mvc?

I've attempted installing the 3.0 (alpha-release), and using the various approaches suggested in sample files and [here](https://github.com/AppMetrics/AppMetrics/issues/261), as well as tutorials without any luck.

Seems like #36 is related to this also?

**Comment by alhardy** [comment]
@Kickeskov does https://github.com/AppMetrics/AspNetCore/issues/36#issuecomment-443190468 resolve your issue?

**Comment by Kickeskov** [comment]
@alhardy Unfortunately we never got it working and went with another solution. Can't remember if we tried this.

**Comment by alhardy** [comment]
Versioning in route template appears as `v{version:apiversion}`

**Comment by anktsrkr** [comment]
hey @alhardy  thanks for this great library! 

As per my attached screenshot, proper version is not showing, even if  I tried with supported version of that API.
 
![image](https://user-images.githubusercontent.com/5505886/52472041-5fa2ea80-2bb8-11e9-8d89-ffd4aad90fc3.png)

Also, I am expecting to see the actual "Id", instead of placeholder in case of PUT request. am i missing something?

Please advise. Thanks!

**Comment by alhardy** [comment]
Thanks @anktsrkr.

That's a known issue re versioning. Planning to look into this soon.

Re the `{id}` param, it's expected to report template param name. You could however write your own middleware to report the value instead, it all depends on what your measuring in the case of the default asp.net core middleware it's about visualising the throughput of each endpoint.
