### ISSUE TITLE
Improve Check for multiple instantiations 

### ISSUE THREAD

**Issue by Decad** [AppMetrics/AspNetCore#5]
Currently the check for multiple instantiations is done via the static bool property [_metricsBuilt](https://github.com/AppMetrics/AspNetCore/blob/dev/src/App.Metrics.AspNetCore.Hosting/MetricsAspNetWebHostBuilderExtensions.cs#L19). Which will throw the an InvalidOperationException if that bool is set to true when someone calls one of the WebHostBuilderExtension methods. This works fine in the 'normal' use case when you would expect only one instance of AppMetrics in that program. However if you attempt to test your website/api with `Microsoft.AspNetCore.TestHost.TestServer` its possible that you would want to standup and teardown multiple different configurations under test. In this use case the static bool will be set to true after the first TestServer has been created and then error for any other instances even though the appmetrics services haven't been registered for that instance.

Can we change the way this check is done, the ASP.NET MVC project use a [MvcMarkerService](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcMarkerService.cs) that they check for inside the `IServiceCollection` to determine if they already registered their services.

I have done a rough pass at these changes to help illustrate the idea on https://github.com/countrywide/AspNetCore/commit/afdcf967dd03d9f5b48c4a136fca17a3c3e35727

We are able to work around this by having one single instance that we share between our tests but we are unable to test changes to our startup configuration due to this design.

Thanks

**Comment by alhardy** [comment]
@Decad thanks for the details. I would prefer not to force `IServiceProvider` to be built more than once.

I'll have a think about your scenario.

**Comment by alhardy** [comment]
I'd prefer to leave this as is, as mentioned I don't think its a good idea to have App Metrics build the `IServiceProvider` without the user knowing.

I do use the Marker Service approach in other cases when the service provider is already built, in this particular case it is before the fact, ASP.NET Hosting also uses a static variable to ensure only one instance of `IWebHost`, see [here](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L146).

In your case re "setup and tear down multiple different configurations under test", could you take a similar approach to that used in `App.Metrics.AspNetCore.Integration.Facts` where `IClassFixture`s are used?

I would rather have an exception thrown if multiple instances of `IMetrics`  are accidentally attempted to be registered through App Metrics configuration since allowing it could cause run-time confusion. 

Thoughts?
